// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>DealerSafe.DTO.Epp.Protocol.PremiumDomain</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace DealerSafe.DTO.Epp.Protocol.PremiumDomain
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign.com/epp/premiumdomain-1.0")]
    [System.Xml.Serialization.XmlRootAttribute("check", Namespace = "http://www.verisign.com/epp/premiumdomain-1.0", IsNullable = false)]
    public partial class chkType : GeneratedEppEntity<chkType>
    {

        private bool flagField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public bool flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign.com/epp/premiumdomain-1.0")]
    [System.Xml.Serialization.XmlRootAttribute("chkData", Namespace = "http://www.verisign.com/epp/premiumdomain-1.0", IsNullable = false)]
    public partial class chkDataType : GeneratedEppEntity<chkDataType>
    {

        private List<checkType> cdField;

        /// <summary>
        /// chkDataType class constructor
        /// </summary>
        public chkDataType()
        {
            this.cdField = new List<checkType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("cd", Order = 0)]
        public List<checkType> cd
        {
            get
            {
                return this.cdField;
            }
            set
            {
                this.cdField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign.com/epp/premiumdomain-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.verisign.com/epp/premiumdomain-1.0", IsNullable = true)]
    public partial class checkType : GeneratedEppEntity<checkType>
    {

        private checkNameType nameField;

        private priceType priceField;

        private priceType renewalPriceField;

        /// <summary>
        /// checkType class constructor
        /// </summary>
        public checkType()
        {
            this.renewalPriceField = new priceType();
            this.priceField = new priceType();
            this.nameField = new checkNameType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public checkNameType name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public priceType price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public priceType renewalPrice
        {
            get
            {
                return this.renewalPriceField;
            }
            set
            {
                this.renewalPriceField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign.com/epp/premiumdomain-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.verisign.com/epp/premiumdomain-1.0", IsNullable = true)]
    public partial class checkNameType : GeneratedEppEntity<checkNameType>
    {

        private bool premiumField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool premium
        {
            get
            {
                return this.premiumField;
            }
            set
            {
                this.premiumField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign.com/epp/premiumdomain-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.verisign.com/epp/premiumdomain-1.0", IsNullable = true)]
    public partial class priceType : GeneratedEppEntity<priceType>
    {

        private priceUnitType unitField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public priceUnitType unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }

         [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign.com/epp/premiumdomain-1.0")]
    public enum priceUnitType
    {

        /// <remarks/>
        USD,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign.com/epp/premiumdomain-1.0")]
    [System.Xml.Serialization.XmlRootAttribute("reassign", Namespace = "http://www.verisign.com/epp/premiumdomain-1.0", IsNullable = false)]
    public partial class reassignType : GeneratedEppEntity<reassignType>
    {

        private string shortNameField;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 0)]
        public string shortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }
    }
}
