//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealerSafe.DTO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DealerSafe.DTO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;http://www.verisign.com/epp/balance-1.0&quot;
        ///	xmlns:balance=&quot;http://www.verisign.com/epp/balance-1.0&quot;
        ///	xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///	&lt;annotation&gt;
        ///		&lt;documentation&gt;
        ///		Extensible Provisioning Protocol v1.0
        ///		Verisign mapping for getting account balance and other financial
        ///		information.
        ///		&lt;/documentation&gt;
        ///	&lt;/annotation&gt;
        ///	&lt;!--Child elements found in EPP commands.--&gt;
        ///	&lt;!-- Empty balance:info c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string balance_1_0 {
            get {
                return ResourceManager.GetString("balance_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;http://www.unitedtld.com/epp/charge-1.0&quot; xmlns:charge=&quot;http://www.unitedtld.com/epp/charge-1.0&quot; xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///	&lt;import namespace=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot; schemaLocation=&quot;eppcom-1.0.xsd&quot; /&gt;
        ///	&lt;annotation&gt;
        ///		&lt;documentation&gt;
        ///			Extensible Provisioning Protocol v1.0 domain name extension schema for domains part of a charge se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string charge_1_0 {
            get {
                return ResourceManager.GetString("charge_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///  &lt;schema targetNamespace=&quot;urn:ietf:params:xml:ns:contact-1.0&quot;
        ///          xmlns:contact=&quot;urn:ietf:params:xml:ns:contact-1.0&quot;
        ///          xmlns:epp=&quot;urn:ietf:params:xml:ns:epp-1.0&quot;
        ///          xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///          xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///          elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;!--
        ///  Import common element types.
        ///  --&gt;
        ///    &lt;import namespace=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///            schemaLocation=&quot;eppcom-1.0.x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contact_1_0 {
            get {
                return ResourceManager.GetString("contact_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:ietf:params:xml:ns:contact-1.0 contact-1.0.xsd.
        /// </summary>
        internal static string ContactSchemaLocation {
            get {
                return ResourceManager.GetString("ContactSchemaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///  &lt;schema targetNamespace=&quot;urn:ietf:params:xml:ns:domain-1.0&quot;
        ///          xmlns:domain=&quot;urn:ietf:params:xml:ns:domain-1.0&quot;
        ///          xmlns:host=&quot;urn:ietf:params:xml:ns:host-1.0&quot;
        ///          xmlns:epp=&quot;urn:ietf:params:xml:ns:epp-1.0&quot;
        ///          xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///          xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///          elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;!--
        ///  Import common element types.
        ///  --&gt;
        ///    &lt;import namespace=&quot;urn:ietf:params:xml:ns: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string domain_1_0 {
            get {
                return ResourceManager.GetString("domain_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:ietf:params:xml:ns:domain-1.0 domain-1.0.xsd.
        /// </summary>
        internal static string DomainSchemaLocation {
            get {
                return ResourceManager.GetString("DomainSchemaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///  &lt;schema targetNamespace=&quot;urn:ietf:params:xml:ns:epp-1.0&quot;
        ///          xmlns:epp=&quot;urn:ietf:params:xml:ns:epp-1.0&quot;
        ///          xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///          xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///          elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;!--
        ///  Import common element types.
        ///  --&gt;
        ///    &lt;import namespace=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///            schemaLocation=&quot;eppcom-1.0.xsd&quot;/&gt;
        ///
        ///    &lt;annotation&gt;
        ///      &lt;documentation&gt;
        ///        Extensible  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string epp_1_0 {
            get {
                return ResourceManager.GetString("epp_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///  &lt;schema targetNamespace=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///          xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///          xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///          elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///    &lt;annotation&gt;
        ///      &lt;documentation&gt;
        ///        Extensible Provisioning Protocol v1.0
        ///        shared structures schema.
        ///      &lt;/documentation&gt;
        ///    &lt;/annotation&gt;
        ///
        ///  &lt;!--
        ///  Object authorization information types.
        ///  --&gt;
        ///    &lt;complexType name=&quot;pwAuthInfoType&quot;&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eppcom_1_0 {
            get {
                return ResourceManager.GetString("eppcom_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;epp xmlns=&quot;urn:ietf:params:xml:ns:epp-1.0&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///     xsi:schemaLocation=&quot;urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd&quot;&gt;
        ///&lt;/epp&gt;.
        /// </summary>
        internal static string EppMessageBase {
            get {
                return ResourceManager.GetString("EppMessageBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  xmlns:fee=&quot;urn:ietf:params:xml:ns:fee-0.5&quot;
        ///  xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///  xmlns:domain=&quot;urn:ietf:params:xml:ns:domain-1.0&quot;
        ///  targetNamespace=&quot;urn:ietf:params:xml:ns:fee-0.5&quot;
        ///  elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;import namespace=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot; schemaLocation=&quot;eppcom-1.0.xsd&quot; /&gt;
        ///  &lt;import namespace=&quot;urn:ietf:params:xml:ns:domain-1.0&quot; schemaLocation=&quot;domain-1.0.xsd&quot; /&gt;
        ///
        ///  &lt;annot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fee_0_5 {
            get {
                return ResourceManager.GetString("fee_0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  xmlns:fee=&quot;urn:ietf:params:xml:ns:fee-0.6&quot;
        ///  xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///  xmlns:domain=&quot;urn:ietf:params:xml:ns:domain-1.0&quot;
        ///  targetNamespace=&quot;urn:ietf:params:xml:ns:fee-0.6&quot;
        ///  elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;import namespace=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot; /&gt;
        ///  &lt;import namespace=&quot;urn:ietf:params:xml:ns:domain-1.0&quot; /&gt;
        ///
        ///  &lt;annotation&gt;
        ///    &lt;documentation&gt;Extensible Provisioning Protocol
        ///    v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fee_0_6 {
            get {
                return ResourceManager.GetString("fee_0_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  xmlns:fee=&quot;urn:ietf:params:xml:ns:fee-0.7&quot;
        ///  xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///  xmlns:domain=&quot;urn:ietf:params:xml:ns:domain-1.0&quot;
        ///  targetNamespace=&quot;urn:ietf:params:xml:ns:fee-0.7&quot;
        ///  elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;import namespace=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot; schemaLocation=&quot;eppcom-1.0.xsd&quot; /&gt;
        ///  &lt;import namespace=&quot;urn:ietf:params:xml:ns:domain-1.0&quot; schemaLocation=&quot;domain-1.0.xsd&quot; /&gt;
        ///
        ///  &lt;annot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fee_0_7 {
            get {
                return ResourceManager.GetString("fee_0_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:ietf:params:xml:ns:fee-0.7 fee-0.7.xsd.
        /// </summary>
        internal static string FeeSchemaLocation {
            get {
                return ResourceManager.GetString("FeeSchemaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;http://www.unitedtld.com/epp/finance-1.0&quot;
        ///	xmlns:finance=&quot;http://www.unitedtld.com/epp/finance-1.0&quot;
        ///	xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///	elementFormDefault=&quot;qualified&quot;&gt;
        ///	
        ///	&lt;annotation&gt;
        ///		&lt;documentation&gt;
        ///			Extensible Provisioning Protocol v1.0
        ///			Mapping for account balance and thresholds.
        ///		&lt;/documentation&gt;
        ///	&lt;/annotation&gt;
        ///
        ///	&lt;!-- Child elements found in EPP commands. --&gt;
        ///	&lt;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string finance_1_0 {
            get {
                return ResourceManager.GetString("finance_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.unitedtld.com/epp/finance-1.0 finance-1.0.xsd.
        /// </summary>
        internal static string FinanceSchemaLocation {
            get {
                return ResourceManager.GetString("FinanceSchemaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;epp xmlns=&quot;urn:ietf:params:xml:ns:epp-1.0&quot;
        ///     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///     xsi:schemaLocation=&quot;urn:ietf:params:xml:ns:epp-1.0 epp-1.0.xsd&quot;&gt;
        ///  &lt;hello/&gt;
        ///&lt;/epp&gt;
        ///.
        /// </summary>
        internal static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///  &lt;schema targetNamespace=&quot;urn:ietf:params:xml:ns:host-1.0&quot;
        ///          xmlns:host=&quot;urn:ietf:params:xml:ns:host-1.0&quot;
        ///          xmlns:epp=&quot;urn:ietf:params:xml:ns:epp-1.0&quot;
        ///          xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///          xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///          elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;!--
        ///  Import common element types.
        ///  --&gt;
        ///    &lt;import namespace=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///            schemaLocation=&quot;eppcom-1.0.xsd&quot;/&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string host_1_0 {
            get {
                return ResourceManager.GetString("host_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:ietf:params:xml:ns:host-1.0 host-1.0.xsd.
        /// </summary>
        internal static string HostSchemaLocation {
            get {
                return ResourceManager.GetString("HostSchemaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;schema targetNamespace=&quot;http://www.key-systems.net/epp/keysys-1.0&quot;
        ///        xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///        xmlns:epp=&quot;urn:ietf:params:xml:ns:epp-1.0&quot;
        ///        xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///        xmlns:keysys=&quot;http://www.key-systems.net/epp/keysys-1.0&quot;
        ///        elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;annotation&gt;
        ///    &lt;documentation&gt;
        ///      Extensible Provisioning Protocol v1.0 Key-Systems extension schema.
        ///    &lt;/documentation&gt;
        ///  &lt;/annotat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keysys_1_0 {
            get {
                return ResourceManager.GetString("keysys_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;schema
        /// targetNamespace=&quot;urn:ietf:params:xml:ns:launch-1.0&quot;
        /// xmlns:launch=&quot;urn:ietf:params:xml:ns:launch-1.0&quot;
        /// xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        /// xmlns:mark=&quot;urn:ietf:params:xml:ns:mark-1.0&quot;
        /// xmlns:smd=&quot;urn:ietf:params:xml:ns:signedMark-1.0&quot;
        /// xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        /// elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///&lt;!--
        ///Import common element types.
        ///--&gt;
        /// &lt;import namespace=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///		 schemaLocation=&quot;eppcom-1.0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string launch_1_0 {
            get {
                return ResourceManager.GetString("launch_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:ietf:params:xml:ns:launch-1.0 launch-1.0.xsd.
        /// </summary>
        internal static string LaunchSchemaLocation {
            get {
                return ResourceManager.GetString("LaunchSchemaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        /// 
        /// &lt;schema
        ///   targetNamespace=&quot;urn:ietf:params:xml:ns:mark-1.0&quot;
        ///   xmlns:mark=&quot;urn:ietf:params:xml:ns:mark-1.0&quot;
        ///   xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///   elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///   &lt;annotation&gt;
        ///     &lt;documentation&gt;
        ///       Schema for representing a Trademark, also referred to
        ///       as Mark.
        ///     &lt;/documentation&gt;
        ///   &lt;/annotation&gt;
        ///
        ///   &lt;!--
        ///   Abstract mark for replacement via substitution.
        ///   --&gt;
        ///   &lt;element name=&quot;abstractMark&quot; type=&quot;mark [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mark_1_0 {
            get {
                return ResourceManager.GetString("mark_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;http://www.verisign-grs.com/epp/namestoreExt-1.1&quot;
        ///	xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:namestoreExt=&quot;http://www.verisign-grs.com/epp/namestoreExt-1.1&quot;
        ///	elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;annotation&gt;
        ///		&lt;documentation&gt;
        ///		Extensible Provisioning Protocol v1.0 Namestore extension schema
        ///		for destination registry routing.
        ///		&lt;/documentation&gt;
        ///	&lt;/annotation&gt;
        ///	&lt;!-- General Data types. --&gt;
        ///	&lt;simpleType name=&quot;subProductType&quot;&gt;
        ///		&lt;r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string namestoreExt_1_1 {
            get {
                return ResourceManager.GetString("namestoreExt_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;http://www.verisign.com/epp/premiumdomain-1.0&quot;
        ///	xmlns:premiumdomain=&quot;http://www.verisign.com/epp/premiumdomain-1.0&quot;
        ///	xmlns:eppcom=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot;
        ///	xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	elementFormDefault=&quot;qualified&quot;&gt;
        ///	
        ///	&lt;!-- Import common element types. --&gt;
        ///	&lt;import namespace=&quot;urn:ietf:params:xml:ns:eppcom-1.0&quot; schemaLocation=&quot;eppcom-1.0.xsd&quot;/&gt;
        ///
        ///	&lt;annotation&gt;
        ///		&lt;documentation&gt;
        ///			Extensible Provisioning Proto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string premiumdomain_1_0 {
            get {
                return ResourceManager.GetString("premiumdomain_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///        targetNamespace=&quot;urn:afilias:params:xml:ns:price-1.0&quot;
        ///        xmlns:price=&quot;urn:afilias:params:xml:ns:price-1.0&quot;
        ///        elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;annotation&gt;
        ///    &lt;documentation&gt;
        ///      Extensible Provisioning Protocol v1.0
        ///      domain name extension schema for premium pricing
        ///    &lt;/documentation&gt;
        ///  &lt;/annotation&gt;
        ///
        ///
        ///
        ///  &lt;!--
        ///    response elements
        ///  --&gt;
        ///  
        /// 
        ///  &lt;element name=&quot;chkData&quot; t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string price_1_0 {
            get {
                return ResourceManager.GetString("price_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;urn:ietf:params:xml:ns:rgp-1.0&quot;
        ///           xmlns:rgp=&quot;urn:ietf:params:xml:ns:rgp-1.0&quot;
        ///           xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///     &lt;annotation&gt;
        ///       &lt;documentation&gt;
        ///         Extensible Provisioning Protocol v1.0
        ///         domain name extension schema for registry grace period
        ///         processing.
        ///       &lt;/documentation&gt;
        ///     &lt;/annotation&gt;
        ///
        ///   &lt;!--
        ///   Child elements found in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rgp_1_0 {
            get {
                return ResourceManager.GetString("rgp_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///   &lt;schema targetNamespace=&quot;urn:ietf:params:xml:ns:secDNS-1.0&quot;
        ///           xmlns:secDNS=&quot;urn:ietf:params:xml:ns:secDNS-1.0&quot;
        ///           xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///     &lt;annotation&gt;
        ///       &lt;documentation&gt;
        ///         Extensible Provisioning Protocol v1.0
        ///         domain name extension schema for provisioning
        ///         DNS security (DNSSEC) extensions.
        ///       &lt;/documentation&gt;
        ///     &lt;/annotation&gt;
        ///
        ///   &lt;!--        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string secDNS_1_0 {
            get {
                return ResourceManager.GetString("secDNS_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:ietf:params:xml:ns:secDNS-1.0 secDNS-1.0.xsd.
        /// </summary>
        internal static string SecDnsSchemaLocation {
            get {
                return ResourceManager.GetString("SecDnsSchemaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;schema
        ///targetNamespace=&quot;urn:ietf:params:xml:ns:signedMark-1.0&quot;
        ///xmlns:smd=&quot;urn:ietf:params:xml:ns:signedMark-1.0&quot;
        ///xmlns:mark=&quot;urn:ietf:params:xml:ns:mark-1.0&quot;
        ///xmlns:dsig=&quot;http://www.w3.org/2000/09/xmldsig#&quot;
        ///xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///&lt;annotation&gt;
        ///  &lt;documentation&gt;
        ///	Schema for representing a Signed Trademark.
        ///  &lt;/documentation&gt;
        ///&lt;/annotation&gt;
        ///
        ///&lt;import namespace=&quot;urn:ietf:params:xml:ns:mark-1.0&quot;
        ///  schemaLoca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string signedMark_1_0 {
            get {
                return ResourceManager.GetString("signedMark_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;!-- Schema for XML Signatures
        ///    http://www.w3.org/2000/09/xmldsig#
        ///    $Revision: 1.1 $ on $Date: 2002/02/08 20:32:26 $ by $Author: reagle $
        ///
        ///    Copyright 2001 The Internet Society and W3C (Massachusetts Institute
        ///    of Technology, Institut National de Recherche en Informatique et en
        ///    Automatique, Keio University). All Rights Reserved.
        ///    http://www.w3.org/Consortium/Legal/
        ///
        ///    This document is governed by the W3C Software License [1] as described
        ///    in the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xmldsig_core_schema {
            get {
                return ResourceManager.GetString("xmldsig_core_schema", resourceCulture);
            }
        }
    }
}
