// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>DealerSafe.DTO.Epp.Protocol.NameStore</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace DealerSafe.DTO.Epp.Protocol.NameStore
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign-grs.com/epp/namestoreExt-1.1")]
    [System.Xml.Serialization.XmlRootAttribute("namestoreExt", Namespace = "http://www.verisign-grs.com/epp/namestoreExt-1.1", IsNullable = false)]
    public partial class namestoreExtType : GeneratedEppEntity<namestoreExtType>
    {

        private string subProductField;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 0)]
        public string subProduct
        {
            get
            {
                return this.subProductField;
            }
            set
            {
                this.subProductField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign-grs.com/epp/namestoreExt-1.1")]
    [System.Xml.Serialization.XmlRootAttribute("nsExtErrData", Namespace = "http://www.verisign-grs.com/epp/namestoreExt-1.1", IsNullable = false)]
    public partial class nsExtErrDataType : GeneratedEppEntity<nsExtErrDataType>
    {

        private msgType msgField;

        /// <summary>
        /// nsExtErrDataType class constructor
        /// </summary>
        public nsExtErrDataType()
        {
            this.msgField = new msgType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public msgType msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign-grs.com/epp/namestoreExt-1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.verisign-grs.com/epp/namestoreExt-1.1", IsNullable = true)]
    public partial class msgType : GeneratedEppEntity<msgType>
    {

        private ushort codeField;

        private string langField;

        private string valueField;

        public msgType()
        {
            this.langField = "en";
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        [System.ComponentModel.DefaultValueAttribute("en")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "normalizedString")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.verisign-grs.com/epp/namestoreExt-1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.verisign-grs.com/epp/namestoreExt-1.1", IsNullable = true)]
    public partial class extAnyType : GeneratedEppEntity<extAnyType>
    {

        private List<System.Xml.XmlElement> anyField;

        /// <summary>
        /// extAnyType class constructor
        /// </summary>
        public extAnyType()
        {
            this.anyField = new List<System.Xml.XmlElement>();
        }

        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public List<System.Xml.XmlElement> Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
}
