// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>DealerSafe.DTO</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Linq;

namespace DealerSafe.DTO.Epp.Protocol.Price
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    [System.Xml.Serialization.XmlRootAttribute("chkData", Namespace = "urn:afilias:params:xml:ns:price-1.0", IsNullable = false)]
    public partial class chkDataType : GeneratedEppEntity<chkDataType>
    {

        private List<cdType> cdField;

        public chkDataType()
        {
            this.cdField = new List<cdType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("cd", Order = 0)]
        public List<cdType> cd
        {
            get
            {
                return this.cdField;
            }
            set
            {
                this.cdField = value;
            }
        }

        public cdType getByDomainName(string domainName)
        {
            return cd.FirstOrDefault(i => i.domain.Value.ToLowerInvariant() == domainName.ToLowerInvariant());
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0", IsNullable = true)]
    public partial class cdType : GeneratedEppEntity<cdType>
    {

        private domainType domainField;

        private string currencyField;

        private periodType periodField;

        private List<pricingType> pricingField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string currency { get; set; }


        public cdType()
        {
            this.pricingField = new List<pricingType>();
            this.periodField = new periodType();
            this.domainField = new domainType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public domainType domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public periodType period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("pricing", Order = 3)]
        public List<pricingType> pricing
        {
            get
            {
                return this.pricingField;
            }
            set
            {
                this.pricingField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0", IsNullable = true)]
    public partial class domainType : GeneratedEppEntity<domainType>
    {

        private string valueField;

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }


        [System.Xml.Serialization.XmlAttributeAttribute()]
        public domainPriceType type
        {
            get
            {
                return domainPriceType.premium;
            }
            set
            {
                //this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    public enum domainPriceType
    {

        /// <remarks/>
        premium,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0", IsNullable = true)]
    public partial class amountType : GeneratedEppEntity<amountType>
    {

        private decimal valueField;

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }


        private operationType typeField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public operationType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    public enum operationType
    {

        /// <remarks/>
        create,

        /// <remarks/>
        renew,

        /// <remarks/>
        transfer,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0", IsNullable = true)]
    public partial class pricingType : GeneratedEppEntity<pricingType>
    {

        private List<amountType> amountField;

        private System.DateTime fromField;

        private bool fromFieldSpecified;

        private System.DateTime toField;

        private bool toFieldSpecified;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime from { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime to { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toSpecified { get; set; }


        public pricingType()
        {
            this.amountField = new List<amountType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("amount", Order = 0)]
        public List<amountType> amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0", IsNullable = true)]
    public partial class periodType : GeneratedEppEntity<periodType>
    {

        private string unitField;

        private int valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unit { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    [System.Xml.Serialization.XmlRootAttribute("creData", Namespace = "urn:afilias:params:xml:ns:price-1.0", IsNullable = false)]
    public partial class creDataType : GeneratedEppEntity<creDataType>
    {

        private domainType domainField;

        public creDataType()
        {
            this.domainField = new domainType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public domainType domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    [System.Xml.Serialization.XmlRootAttribute("trnData", Namespace = "urn:afilias:params:xml:ns:price-1.0", IsNullable = false)]
    public partial class trnDataType : GeneratedEppEntity<trnDataType>
    {

        private domainType domainField;

        public trnDataType()
        {
            this.domainField = new domainType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public domainType domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:afilias:params:xml:ns:price-1.0")]
    [System.Xml.Serialization.XmlRootAttribute("renData", Namespace = "urn:afilias:params:xml:ns:price-1.0", IsNullable = false)]
    public partial class renDataType : GeneratedEppEntity<renDataType>
    {

        private domainType domainField;

        public renDataType()
        {
            this.domainField = new domainType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public domainType domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
    }
}
