// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>DealerSafe.DTO.Epp.Protocol.Rgp</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace DealerSafe.DTO.Epp.Protocol.Rgp
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0")]
    [System.Xml.Serialization.XmlRootAttribute("update", Namespace = "urn:ietf:params:xml:ns:rgp-1.0", IsNullable = false)]
    public partial class updateType : GeneratedEppEntity<updateType>
    {

        private restoreType restoreField;

        /// <summary>
        /// updateType class constructor
        /// </summary>
        public updateType()
        {
            this.restoreField = new restoreType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public restoreType restore
        {
            get
            {
                return this.restoreField;
            }
            set
            {
                this.restoreField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0", IsNullable = true)]
    public partial class restoreType : GeneratedEppEntity<restoreType>
    {

        private reportType reportField;

        private rgpOpType opField;

        /// <summary>
        /// restoreType class constructor
        /// </summary>
        public restoreType()
        {
            this.reportField = new reportType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public reportType report
        {
            get
            {
                return this.reportField;
            }
            set
            {
                this.reportField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public rgpOpType op
        {
            get
            {
                return this.opField;
            }
            set
            {
                this.opField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0", IsNullable = true)]
    public partial class reportType : GeneratedEppEntity<reportType>
    {

        private mixedType preDataField;

        private mixedType postDataField;

        private System.DateTime delTimeField;

        private System.DateTime resTimeField;

        private reportTextType resReasonField;

        private List<reportTextType> statementField;

        private mixedType otherField;

        /// <summary>
        /// reportType class constructor
        /// </summary>
        public reportType()
        {
            this.otherField = new mixedType();
            this.statementField = new List<reportTextType>();
            this.resReasonField = new reportTextType();
            this.postDataField = new mixedType();
            this.preDataField = new mixedType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public mixedType preData
        {
            get
            {
                return this.preDataField;
            }
            set
            {
                this.preDataField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public mixedType postData
        {
            get
            {
                return this.postDataField;
            }
            set
            {
                this.postDataField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime delTime
        {
            get
            {
                return this.delTimeField;
            }
            set
            {
                this.delTimeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime resTime
        {
            get
            {
                return this.resTimeField;
            }
            set
            {
                this.resTimeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public reportTextType resReason
        {
            get
            {
                return this.resReasonField;
            }
            set
            {
                this.resReasonField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("statement", Order = 5)]
        public List<reportTextType> statement
        {
            get
            {
                return this.statementField;
            }
            set
            {
                this.statementField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public mixedType other
        {
            get
            {
                return this.otherField;
            }
            set
            {
                this.otherField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0", IsNullable = true)]
    public partial class mixedType : GeneratedEppEntity<mixedType>
    {

        private List<string> textField;

        /// <summary>
        /// mixedType class constructor
        /// </summary>
        public mixedType()
        {
            this.textField = new List<string>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0", IsNullable = true)]
    public partial class reportTextType : GeneratedEppEntity<reportTextType>
    {

        private List<string> textField;

        /// <summary>
        /// reportTextType class constructor
        /// </summary>
        public reportTextType()
        {
            this.textField = new List<string>();
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0", IsNullable = true)]
    public partial class statusType : GeneratedEppEntity<statusType>
    {

        private statusValueType sField;

        private string langField;

        private string valueField;

        public statusType()
        {
            this.langField = "en";
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public statusValueType s
        {
            get
            {
                return this.sField;
            }
            set
            {
                this.sField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        [System.ComponentModel.DefaultValueAttribute("en")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "normalizedString")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0")]
    public enum statusValueType
    {

        /// <remarks/>
        addPeriod,

        /// <remarks/>
        autoRenewPeriod,

        /// <remarks/>
        renewPeriod,

        /// <remarks/>
        transferPeriod,

        /// <remarks/>
        pendingDelete,

        /// <remarks/>
        pendingRestore,

        /// <remarks/>
        redemptionPeriod,

        NONE
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0")]
    public enum rgpOpType
    {

        /// <remarks/>
        request,

        /// <remarks/>
        report,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:ietf:params:xml:ns:rgp-1.0")]
    [System.Xml.Serialization.XmlRootAttribute("infData", Namespace = "urn:ietf:params:xml:ns:rgp-1.0", IsNullable = false)]
    public partial class respDataType : GeneratedEppEntity<respDataType>
    {

        private List<statusType> rgpStatusField;

        /// <summary>
        /// respDataType class constructor
        /// </summary>
        public respDataType()
        {
            this.rgpStatusField = new List<statusType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("rgpStatus", Order = 0)]
        public List<statusType> rgpStatus
        {
            get
            {
                return this.rgpStatusField;
            }
            set
            {
                this.rgpStatusField = value;
            }
        }
    }
}
