// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>DealerSafe.DTO</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Linq;

namespace DealerSafe.DTO.Epp.Protocol.Fee06 {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute("check", Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=false)]
    public partial class checkType : GeneratedEppEntity<checkType> {
        
        private List<domainCheckType> domainField;
        
        /// <summary>
        /// checkType class constructor
        /// </summary>
        public checkType() {
            this.domainField = new List<domainCheckType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("domain", Order=0)]
        public List<domainCheckType> domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=true)]
    public partial class domainCheckType : GeneratedEppEntity<domainCheckType> {
        
        
        private commandType commandField;
        
        private periodType periodField;
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="token",Order=0)]
    public string name {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string currency {get; set;}

        
        /// <summary>
        /// domainCheckType class constructor
        /// </summary>
        public domainCheckType() {
            this.periodField = new periodType();
            this.commandField = new commandType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public commandType command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public periodType period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=true)]
    public partial class commandType : GeneratedEppEntity<commandType> {
        
        
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string phase {get; set;}

    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string subphase {get; set;}

    [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
    public string Value {get; set;}

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:domain-1.0")]
    public partial class periodType : GeneratedEppEntity<periodType> {
        
         
        [XmlIgnore]

    public ushort Value {get; set;}

        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string ValueAsString
        {
            get { return Value.ToString(); }
            set { }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public pUnitType unit {
            get;
            set ;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:domain-1.0")]
    public enum pUnitType {
        
        /// <remarks/>
        y,
        
        /// <remarks/>
        m,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute("chkData", Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=false)]
    public partial class chkDataType : GeneratedEppEntity<chkDataType> {
        
        private List<domainCDType> cdField;
        
        /// <summary>
        /// chkDataType class constructor
        /// </summary>
        public chkDataType() {
            this.cdField = new List<domainCDType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("cd", Order=0)]
        public List<domainCDType> cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }

        public domainCDType getByDomainName(string domainName)
        {
            return cdField.FirstOrDefault(i => i.name.ToLowerInvariant()  == domainName.ToLowerInvariant());
        }

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=true)]
    public partial class domainCDType : GeneratedEppEntity<domainCDType> {
        
         
        private commandType commandField;
        
        private periodType periodField;
        
        private List<feeType> feeField;

        public bool premium;
        
        
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string name {get; set;}

    [System.Xml.Serialization.XmlElementAttribute()]
    public string currency {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string @class {get; set;}

        
        /// <summary>
        /// domainCDType class constructor
        /// </summary>
        public domainCDType() {
            this.feeField = new List<feeType>();
            this.periodField = new periodType();
            this.commandField = new commandType();
            this.@class = "standard";
        }
        
        [System.Xml.Serialization.XmlElementAttribute()]
        public commandType command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute()]
        public periodType period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("fee")]
        public List<feeType> fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=true)]
    public partial class feeType : GeneratedEppEntity<feeType> {
        
        
        private bool refundableField;
        
        private string graceperiodField;
        
        private feeTypeApplied appliedField;
        
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {get; set;}

    [System.Xml.Serialization.XmlAttributeAttribute("grace-period",DataType="duration")]
    public string graceperiod {get; set;}

    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {get; set;}

        
        public feeType() {
            this.refundableField = true;
            this.graceperiodField = "P0D";
            this.appliedField = feeTypeApplied.immediate;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool refundable {
            get {
                return this.refundableField;
            }
            set {
                this.refundableField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(feeTypeApplied.immediate)]
        public feeTypeApplied applied {
            get {
                return this.appliedField;
            }
            set {
                this.appliedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    public enum feeTypeApplied {
        
        /// <remarks/>
        immediate,
        
        /// <remarks/>
        delayed,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute("info", Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=false)]
    public partial class infoType : GeneratedEppEntity<infoType> {
        
        
        private commandType commandField;
        
        private periodType periodField;
        
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string currency {get; set;}

        
        /// <summary>
        /// infoType class constructor
        /// </summary>
        public infoType() {
            this.periodField = new periodType();
            this.commandField = new commandType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public commandType command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public periodType period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute("infData", Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=false)]
    public partial class infDataType : GeneratedEppEntity<infDataType> {
        
        
        private commandType commandField;
        
        private periodType periodField;
        
        private List<feeType> feeField;
        
        
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string currency {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(DataType="token",Order=4)]
    public string _class {get; set;}

        
        /// <summary>
        /// infDataType class constructor
        /// </summary>
        public infDataType() {
            this.feeField = new List<feeType>();
            this.periodField = new periodType();
            this.commandField = new commandType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public commandType command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public periodType period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("fee", Order=3)]
        public List<feeType> fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute("create", Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=false)]
    public partial class transformCommandType : GeneratedEppEntity<transformCommandType> {
        
        
        private List<feeType> feeField;
        
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string currency {get; set;}

        
        /// <summary>
        /// transformCommandType class constructor
        /// </summary>
        public transformCommandType() {
            this.feeField = new List<feeType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("fee", Order=1)]
        public List<feeType> fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute("creData", Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=false)]
    public partial class transformResultType : GeneratedEppEntity<transformResultType> {
        
        
        private List<feeType> feeField;
        
        
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string currency {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public decimal balance {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool balanceSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public decimal creditLimit {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creditLimitSpecified {get; set;}

        
        /// <summary>
        /// transformResultType class constructor
        /// </summary>
        public transformResultType() {
            this.feeField = new List<feeType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("fee", Order=1)]
        public List<feeType> fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute("trnData", Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=false)]
    public partial class transferResultType : GeneratedEppEntity<transferResultType> {
        
       
        private periodType periodField;
        
        private List<feeType> feeField;
        
        
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string currency {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public decimal balance {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool balanceSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public decimal creditLimit {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creditLimitSpecified {get; set;}

        
        /// <summary>
        /// transferResultType class constructor
        /// </summary>
        public transferResultType() {
            this.feeField = new List<feeType>();
            this.periodField = new periodType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public periodType period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("fee", Order=2)]
        public List<feeType> fee {
            get {
                return this.feeField;
            }
            set {
                this.feeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute("delData", Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=false)]
    public partial class deleteDataType : GeneratedEppEntity<deleteDataType> {
        
        
        private List<creditType> creditField;
        
        
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string currency {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public decimal balance {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool balanceSpecified {get; set;}

    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public decimal creditLimit {get; set;}

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creditLimitSpecified {get; set;}

        
        /// <summary>
        /// deleteDataType class constructor
        /// </summary>
        public deleteDataType() {
            this.creditField = new List<creditType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("credit", Order=1)]
        public List<creditType> credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ietf:params:xml:ns:fee-0.6", IsNullable=true)]
    public partial class creditType : GeneratedEppEntity<creditType> {
        
        
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {get; set;}

    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {get; set;}

    }
}
